const STATIONS = [
  { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
  { code: 'NZM', name: 'Hazrat Nizamuddin', city: 'Delhi' },
  { code: 'DEE', name: 'Delhi Sarai Rohilla', city: 'Delhi' },
  { code: 'DLI', name: 'Old Delhi', city: 'Delhi' },
  { code: 'ANVT', name: 'Anand Vihar Terminal', city: 'Delhi' },
  { code: 'SZM', name: 'Delhi Sabzi Mandi', city: 'Delhi' },
  { code: 'DSA', name: 'Delhi Shahdara', city: 'Delhi' },
  { code: 'GZB', name: 'Ghaziabad Junction', city: 'Ghaziabad' },
  { code: 'FBG', name: 'Faridabad', city: 'Faridabad' },
  { code: 'GRE', name: 'Gurugram Railway Station', city: 'Gurugram' },
  { code: 'LKO', name: 'Lucknow NR', city: 'Lucknow' },
  { code: 'CNB', name: 'Kanpur Central', city: 'Kanpur' },
  { code: 'PRYJ', name: 'Prayagraj Junction', city: 'Prayagraj' },
  { code: 'ALY', name: 'Prayagraj Chheoki', city: 'Prayagraj' },
  { code: 'AGC', name: 'Agra Cantt', city: 'Agra' },
  { code: 'AF', name: 'Agra Fort', city: 'Agra' },
  { code: 'JHS', name: 'Jhansi Junction', city: 'Jhansi' },
  { code: 'GWL', name: 'Gwalior Junction', city: 'Gwalior' },
  { code: 'MTJ', name: 'Mathura Junction', city: 'Mathura' },
  { code: 'MB', name: 'Moradabad Junction', city: 'Moradabad' },
  { code: 'BE', name: 'Bareilly Junction', city: 'Bareilly' },
  { code: 'BPY', name: 'Budaun', city: 'Budaun' },
  { code: 'SHG', name: 'Shahganj Junction', city: 'Shahganj' },
  { code: 'AY', name: 'Ayodhya Dham Junction', city: 'Ayodhya' },
  { code: 'SLN', name: 'Sultanpur Junction', city: 'Sultanpur' },
  { code: 'AMH', name: 'Azamgarh', city: 'Azamgarh' },
  { code: 'GKP', name: 'Gorakhpur Junction', city: 'Gorakhpur' },
  { code: 'BUI', name: 'Basti', city: 'Basti' },
  { code: 'NTV', name: 'Nautanwa', city: 'Nautanwa' },
  { code: 'BSBS', name: 'Banaras', city: 'Varanasi' },
  { code: 'BSB', name: 'Varanasi Junction', city: 'Varanasi' },
  { code: 'OPL', name: 'Orai', city: 'Orai' },
  { code: 'ETW', name: 'Etawah Junction', city: 'Etawah' },
  { code: 'FBD', name: 'Farrukhabad', city: 'Farrukhabad' },
  { code: 'HPU', name: 'Hathras Junction', city: 'Hathras' },
  { code: 'SKB', name: 'Shikohabad Junction', city: 'Shikohabad' },
  { code: 'MFP', name: 'Muzaffarpur Junction', city: 'Muzaffarpur' },
  { code: 'SV', name: 'Siwan Junction', city: 'Siwan' },
  { code: 'KSV', name: 'Kosi Kalan', city: 'Mathura' },
  { code: 'TDL', name: 'Tundla Junction', city: 'Tundla' },
  { code: 'CSTM', name: 'Mumbai CST', city: 'Mumbai' },
  { code: 'BCT', name: 'Mumbai Central', city: 'Mumbai' },
  { code: 'LTT', name: 'Lokmanya Tilak Terminus', city: 'Mumbai' },
  { code: 'BKI', name: 'Bandra Terminus', city: 'Mumbai' },
  { code: 'DR', name: 'Dadar Junction', city: 'Mumbai' },
  { code: 'PNVL', name: 'Panvel Junction', city: 'Mumbai' },
  { code: 'KYN', name: 'Kalyan Junction', city: 'Kalyan' },
  { code: 'BVI', name: 'Borivali', city: 'Mumbai' },
  { code: 'PUNE', name: 'Pune Junction', city: 'Pune' },
  { code: 'LONI', name: 'Lonavala', city: 'Lonavala' },
  { code: 'NAG', name: 'Nagpur Junction', city: 'Nagpur' },
  { code: 'NVS', name: 'Nashik Road', city: 'Nashik' },
  { code: 'JL', name: 'Jalgaon Junction', city: 'Jalgaon' },
  { code: 'BSL', name: 'Bhusawal Junction', city: 'Bhusawal' },
  { code: 'MMR', name: 'Manmad Junction', city: 'Manmad' },
  { code: 'SNSI', name: 'Sainagar Shirdi', city: 'Shirdi' },
  { code: 'AJNI', name: 'Ajni', city: 'Nagpur' },
  { code: 'BPQ', name: 'Balharshah', city: 'Balharshah' },
  { code: 'SEVM', name: 'Sewagram Junction', city: 'Wardha' },
  { code: 'WRL', name: 'Wardha Junction', city: 'Wardha' },
  { code: 'AK', name: 'Akola Junction', city: 'Akola' },
  { code: 'BD', name: 'Badnera Junction', city: 'Amravati' },
  { code: 'SUR', name: 'Solapur Junction', city: 'Solapur' },
  { code: 'KOP', name: 'Kolhapur', city: 'Kolhapur' },
  { code: 'MRJ', name: 'Miraj Junction', city: 'Miraj' },
  { code: 'PVR', name: 'Pandharpur', city: 'Pandharpur' },
  { code: 'MUG', name: 'Mughal Sarai', city: 'Chandauli' },
  { code: 'DMN', name: 'Dhamangaon', city: 'Dhamangaon' },
  { code: 'ADI', name: 'Ahmedabad Junction', city: 'Ahmedabad' },
  { code: 'SBI', name: 'Sabarmati Junction', city: 'Ahmedabad' },
  { code: 'BRC', name: 'Vadodara Junction', city: 'Vadodara' },
  { code: 'ST', name: 'Surat', city: 'Surat' },
  { code: 'BL', name: 'Valsad', city: 'Valsad' },
  { code: 'VAPI', name: 'Vapi', city: 'Vapi' },
  { code: 'NAD', name: 'Nagda Junction', city: 'Nagda' },
  { code: 'ND', name: 'Navsari', city: 'Navsari' },
  { code: 'ANND', name: 'Anand Junction', city: 'Anand' },
  { code: 'NDL', name: 'Nadiad Junction', city: 'Nadiad' },
  { code: 'RTM', name: 'Ratlam Junction', city: 'Ratlam' },
  { code: 'RJT', name: 'Rajkot Junction', city: 'Rajkot' },
  { code: 'PBR', name: 'Porbandar', city: 'Porbandar' },
  { code: 'JAM', name: 'Jamnagar', city: 'Jamnagar' },
  { code: 'BHUJ', name: 'Bhuj', city: 'Bhuj' },
  { code: 'OKHA', name: 'Okha', city: 'Okha' },
  { code: 'GIMB', name: 'Gandhidham Junction', city: 'Gandhidham' },
  { code: 'KUV', name: 'Kandla Port', city: 'Gandhidham' },
  { code: 'PJT', name: 'Patan', city: 'Patan' },
  { code: 'MBT', name: 'Mehsana Junction', city: 'Mehsana' },
  { code: 'HMT', name: 'Himatnagar', city: 'Himatnagar' },
  { code: 'VRL', name: 'Veraval', city: 'Veraval' },
  { code: 'JND', name: 'Junagadh Junction', city: 'Junagadh' },
  { code: 'VDA', name: 'Vasad Junction', city: 'Vasad' },
  { code: 'CLX', name: 'Chirala', city: 'Chirala' },
  { code: 'JP', name: 'Jaipur Junction', city: 'Jaipur' },
  { code: 'JU', name: 'Jodhpur Junction', city: 'Jodhpur' },
  { code: 'UDZ', name: 'Udaipur City', city: 'Udaipur' },
  { code: 'AII', name: 'Ajmer Junction', city: 'Ajmer' },
  { code: 'BKN', name: 'Bikaner Junction', city: 'Bikaner' },
  { code: 'KSG', name: 'Kishangarh', city: 'Kishangarh' },
  { code: 'MJ', name: 'Marwar Junction', city: 'Marwar' },
  { code: 'FA', name: 'Falna', city: 'Falna' },
  { code: 'FL', name: 'Phulera Junction', city: 'Phulera' },
  { code: 'DZ', name: 'Didwana', city: 'Didwana' },
  { code: 'NWH', name: 'Nawalgarh', city: 'Nawalgarh' },
  { code: 'SKA', name: 'Sikar Junction', city: 'Sikar' },
  { code: 'SPT', name: 'Sri Ganganagar', city: 'Sri Ganganagar' },
  { code: 'RTI', name: 'Ratangarh Junction', city: 'Ratangarh' },
  { code: 'CHTT', name: 'Chittorgarh Junction', city: 'Chittorgarh' },
  { code: 'BHL', name: 'Bhilwara', city: 'Bhilwara' },
  { code: 'KOTA', name: 'Kota Junction', city: 'Kota' },
  { code: 'SWM', name: 'Sawai Madhopur', city: 'Sawai Madhopur' },
  { code: 'BGG', name: 'Bharatpur Junction', city: 'Bharatpur' },
  { code: 'RE', name: 'Rewari Junction', city: 'Rewari' },
  { code: 'BPL', name: 'Bhopal Junction', city: 'Bhopal' },
  { code: 'HBJ', name: 'Habibganj', city: 'Bhopal' },
  { code: 'INDB', name: 'Indore Junction', city: 'Indore' },
  { code: 'JBP', name: 'Jabalpur Junction', city: 'Jabalpur' },
  { code: 'ET', name: 'Itarsi Junction', city: 'Itarsi' },
  { code: 'BINA', name: 'Bina Junction', city: 'Bina' },
  { code: 'KYM', name: 'Katni Junction', city: 'Katni' },
  { code: 'UMR', name: 'Umaria', city: 'Umaria' },
  { code: 'SDL', name: 'Shahdol', city: 'Shahdol' },
  { code: 'UJN', name: 'Ujjain Junction', city: 'Ujjain' },
  { code: 'SGO', name: 'Sagar Cantt', city: 'Sagar' },
  { code: 'PPI', name: 'Pipariya', city: 'Pipariya' },
  { code: 'NU', name: 'Narsinghpur', city: 'Narsinghpur' },
  { code: 'MDS', name: 'Mandsaur', city: 'Mandsaur' },
  { code: 'NMH', name: 'Nimach', city: 'Nimach' },
  { code: 'CKTD', name: 'Chitrakoot Dham', city: 'Chitrakoot' },
  { code: 'DAM', name: 'Damoh', city: 'Damoh' },
  { code: 'PTA', name: 'Patna Junction', city: 'Patna' },
  { code: 'RJPB', name: 'Rajendra Nagar Terminal', city: 'Patna' },
  { code: 'PNBE', name: 'Patna Saheb', city: 'Patna' },
  { code: 'GAYA', name: 'Gaya Junction', city: 'Gaya' },
  { code: 'JYG', name: 'Jaynagar', city: 'Jaynagar' },
  { code: 'KIR', name: 'Katihar Junction', city: 'Katihar' },
  { code: 'BGP', name: 'Bhagalpur Junction', city: 'Bhagalpur' },
  { code: 'SHC', name: 'Sahibganj Junction', city: 'Sahibganj' },
  { code: 'NKE', name: 'Narkatiaganj Junction', city: 'Narkatiaganj' },
  { code: 'SEE', name: 'Sonpur Junction', city: 'Sonpur' },
  { code: 'HJP', name: 'Hajipur Junction', city: 'Hajipur' },
  { code: 'MKA', name: 'Mokama Junction', city: 'Mokama' },
  { code: 'KIUL', name: 'Kiul Junction', city: 'Kiul' },
  { code: 'ARA', name: 'Arrah Junction', city: 'Arrah' },
  { code: 'BXR', name: 'Buxar', city: 'Buxar' },
  { code: 'DOS', name: 'Dehri-on-Sone', city: 'Dehri' },
  { code: 'MNE', name: 'Munger', city: 'Munger' },
  { code: 'RNC', name: 'Ranchi Junction', city: 'Ranchi' },
  { code: 'TATA', name: 'Tatanagar Junction', city: 'Jamshedpur' },
  { code: 'DHN', name: 'Dhanbad Junction', city: 'Dhanbad' },
  { code: 'HTE', name: 'Hatia', city: 'Ranchi' },
  { code: 'GMO', name: 'Netaji Subhas Chandra Bose Junction', city: 'Gomoh' },
  { code: 'JSME', name: 'Jasidih Junction', city: 'Jasidih' },
  { code: 'MDP', name: 'Madhupur Junction', city: 'Madhupur' },
  { code: 'CKP', name: 'Chakradharpur', city: 'Chakradharpur' },
  { code: 'ANR', name: 'Anara', city: 'Anara' },
  { code: 'PKU', name: 'Pakur', city: 'Pakur' },
  { code: 'DUMK', name: 'Dumka', city: 'Dumka' },
  { code: 'BBS', name: 'Bhubaneswar', city: 'Bhubaneswar' },
  { code: 'PURI', name: 'Puri', city: 'Puri' },
  { code: 'CTC', name: 'Cuttack Junction', city: 'Cuttack' },
  { code: 'BAM', name: 'Berhampur', city: 'Berhampur' },
  { code: 'BHC', name: 'Bhadrak', city: 'Bhadrak' },
  { code: 'JJKR', name: 'Jajpur Keonjhar Road', city: 'Jajpur' },
  { code: 'DNKL', name: 'Dhenkanal', city: 'Dhenkanal' },
  { code: 'TLHR', name: 'Talcher', city: 'Talcher' },
  { code: 'BSM', name: 'Bolangir', city: 'Bolangir' },
  { code: 'JSG', name: 'Jharsuguda Junction', city: 'Jharsuguda' },
  { code: 'SBP', name: 'Sambalpur Junction', city: 'Sambalpur' },
  { code: 'ROU', name: 'Rourkela', city: 'Rourkela' },
  { code: 'HWH', name: 'Howrah Junction', city: 'Kolkata' },
  { code: 'KOAA', name: 'Kolkata', city: 'Kolkata' },
  { code: 'SDAH', name: 'Sealdah', city: 'Kolkata' },
  { code: 'SHM', name: 'Shalimar', city: 'Kolkata' },
  { code: 'SRC', name: 'Santragachi Junction', city: 'Kolkata' },
  { code: 'NJP', name: 'New Jalpaiguri', city: 'Siliguri' },
  { code: 'MSP', name: 'Malda Town', city: 'Malda' },
  { code: 'KNE', name: 'Kishanganj', city: 'Kishanganj' },
  { code: 'BLH', name: 'Balurghat', city: 'Balurghat' },
  { code: 'BOG', name: 'Bolpur Shantiniketan', city: 'Bolpur' },
  { code: 'SNT', name: 'Sainthia Junction', city: 'Sainthia' },
  { code: 'BPC', name: 'Berhampore Court', city: 'Berhampore' },
  { code: 'AZP', name: 'Azimganj Junction', city: 'Azimganj' },
  { code: 'RSG', name: 'Rampurhat Junction', city: 'Rampurhat' },
  { code: 'ADL', name: 'Adra Junction', city: 'Adra' },
  { code: 'DGR', name: 'Durgapur', city: 'Durgapur' },
  { code: 'JPG', name: 'Jalpaiguri', city: 'Jalpaiguri' },
  { code: 'APC', name: 'Alipurduar Junction', city: 'Alipurduar' },
  { code: 'KNJ', name: 'Krishnanagar City Junction', city: 'Krishnanagar' },
  { code: 'SC', name: 'Secunderabad Junction', city: 'Hyderabad' },
  { code: 'HYB', name: 'Hyderabad Deccan', city: 'Hyderabad' },
  { code: 'KCG', name: 'Kacheguda', city: 'Hyderabad' },
  { code: 'MCTM', name: 'MCTM Secunderabad', city: 'Hyderabad' },
  { code: 'BZA', name: 'Vijayawada Junction', city: 'Vijayawada' },
  { code: 'VSKP', name: 'Visakhapatnam', city: 'Visakhapatnam' },
  { code: 'TPTY', name: 'Tirupati', city: 'Tirupati' },
  { code: 'GDR', name: 'Gudur Junction', city: 'Gudur' },
  { code: 'NLR', name: 'Nellore', city: 'Nellore' },
  { code: 'OGL', name: 'Ongole', city: 'Ongole' },
  { code: 'TDD', name: 'Tadepalligudem', city: 'Tadepalligudem' },
  { code: 'EE', name: 'Eluru', city: 'Eluru' },
  { code: 'AKP', name: 'Anakapalle', city: 'Anakapalle' },
  { code: 'SLO', name: 'Srikakulam Road', city: 'Srikakulam' },
  { code: 'VZM', name: 'Vizianagaram Junction', city: 'Vizianagaram' },
  { code: 'RJY', name: 'Rajahmundry', city: 'Rajahmundry' },
  { code: 'KMI', name: 'Khammam', city: 'Khammam' },
  { code: 'KZJ', name: 'Kazipet Junction', city: 'Warangal' },
  { code: 'WL', name: 'Warangal', city: 'Warangal' },
  { code: 'GNT', name: 'Guntur Junction', city: 'Guntur' },
  { code: 'NDL', name: 'Nandyal Junction', city: 'Nandyal' },
  { code: 'GTL', name: 'Guntakal Junction', city: 'Guntakal' },
  { code: 'HPT', name: 'Hospet Junction', city: 'Hospet' },
  { code: 'BAY', name: 'Bellary Junction', city: 'Bellary' },
  { code: 'KLU', name: 'Kurnool City', city: 'Kurnool' },
  { code: 'AD', name: 'Adoni', city: 'Adoni' },
  { code: 'BAP', name: 'Bellampalli', city: 'Bellampalli' },
  { code: 'RDM', name: 'Ramagundam', city: 'Ramagundam' },
  { code: 'MDR', name: 'Mancherial', city: 'Mancherial' },
  { code: 'NGL', name: 'Nalgonda', city: 'Nalgonda' },
  { code: 'ZN', name: 'Zaheerabad', city: 'Zaheerabad' },
  { code: 'MBNR', name: 'Mahbubnagar', city: 'Mahbubnagar' },
  { code: 'WKI', name: 'Wadi Junction', city: 'Wadi' },
  { code: 'SKZR', name: 'Sirpur Kaghaznagar', city: 'Sirpur Kaghaznagar' },
  { code: 'SBC', name: 'KSR Bengaluru', city: 'Bengaluru' },
  { code: 'BLR', name: 'Bengaluru Cantt', city: 'Bengaluru' },
  { code: 'BNC', name: 'Bengaluru East', city: 'Bengaluru' },
  { code: 'YPR', name: 'Yesvantpur Junction', city: 'Bengaluru' },
  { code: 'KJM', name: 'Krishnarajapuram', city: 'Bengaluru' },
  { code: 'MYS', name: 'Mysuru Junction', city: 'Mysuru' },
  { code: 'UBL', name: 'Hubballi Junction', city: 'Hubballi' },
  { code: 'DWR', name: 'Dharwad', city: 'Dharwad' },
  { code: 'BGM', name: 'Belgaum', city: 'Belgaum' },
  { code: 'KAWR', name: 'Karwar', city: 'Karwar' },
  { code: 'TK', name: 'Tumakuru', city: 'Tumakuru' },
  { code: 'ASPT', name: 'Arsikere Junction', city: 'Arsikere' },
  { code: 'DVG', name: 'Davangere', city: 'Davangere' },
  { code: 'SMET', name: 'Shivamogga Town', city: 'Shivamogga' },
  { code: 'HAS', name: 'Hassan Junction', city: 'Hassan' },
  { code: 'GDG', name: 'Gadag Junction', city: 'Gadag' },
  { code: 'KPT', name: 'Koppal', city: 'Koppal' },
  { code: 'RMGM', name: 'Ramanagaram', city: 'Ramanagaram' },
  { code: 'MADB', name: 'Madikeri', city: 'Madikeri' },
  { code: 'BID', name: 'Bidar', city: 'Bidar' },
  { code: 'MAS', name: 'Chennai Central', city: 'Chennai' },
  { code: 'MS', name: 'Chennai Egmore', city: 'Chennai' },
  { code: 'CBE', name: 'Coimbatore Junction', city: 'Coimbatore' },
  { code: 'MDU', name: 'Madurai Junction', city: 'Madurai' },
  { code: 'SA', name: 'Salem Junction', city: 'Salem' },
  { code: 'TPJ', name: 'Tiruchirappalli Junction', city: 'Tiruchirappalli' },
  { code: 'TN', name: 'Tirunelveli Junction', city: 'Tirunelveli' },
  { code: 'NCJ', name: 'Nagercoil Junction', city: 'Nagercoil' },
  { code: 'RMM', name: 'Rameswaram', city: 'Rameswaram' },
  { code: 'MQ', name: 'Mandapam', city: 'Mandapam' },
  { code: 'ETP', name: 'Erode Junction', city: 'Erode' },
  { code: 'MV', name: 'Mayiladuthurai Junction', city: 'Mayiladuthurai' },
  { code: 'KTM', name: 'Kumbakonam', city: 'Kumbakonam' },
  { code: 'AJJ', name: 'Arakkonam Junction', city: 'Arakkonam' },
  { code: 'KPD', name: 'Katpadi Junction', city: 'Katpadi' },
  { code: 'VLR', name: 'Vellore Cantt', city: 'Vellore' },
  { code: 'VM', name: 'Villupuram Junction', city: 'Villupuram' },
  { code: 'CUPJ', name: 'Cuddalore Port Junction', city: 'Cuddalore' },
  { code: 'KKDI', name: 'Karaikudi Junction', city: 'Karaikudi' },
  { code: 'PDKT', name: 'Pudukkottai', city: 'Pudukkottai' },
  { code: 'VPT', name: 'Virudhunagar Junction', city: 'Virudhunagar' },
  { code: 'SVM', name: 'Sivaganga', city: 'Sivaganga' },
  { code: 'PLNI', name: 'Pollachi Junction', city: 'Pollachi' },
  { code: 'PGN', name: 'Palghat Junction', city: 'Palakkad' },
  { code: 'TVC', name: 'Thiruvananthapuram Central', city: 'Trivandrum' },
  { code: 'ALLP', name: 'Alappuzha', city: 'Alleppey' },
  { code: 'ERS', name: 'Ernakulam Junction', city: 'Kochi' },
  { code: 'ERN', name: 'Ernakulam Town', city: 'Kochi' },
  { code: 'CLT', name: 'Kozhikode', city: 'Calicut' },
  { code: 'MAQ', name: 'Mangalore Central', city: 'Mangalore' },
  { code: 'CAN', name: 'Mangalore Junction', city: 'Mangalore' },
  { code: 'KTYM', name: 'Kottayam', city: 'Kottayam' },
  { code: 'QLN', name: 'Kollam Junction', city: 'Kollam' },
  { code: 'SRR', name: 'Shoranur Junction', city: 'Shoranur' },
  { code: 'PGT', name: 'Palakkad Junction', city: 'Palakkad' },
  { code: 'KMQ', name: 'Kannur', city: 'Kannur' },
  { code: 'CLMD', name: 'Kasargod', city: 'Kasargod' },
  { code: 'TIR', name: 'Tirur', city: 'Tirur' },
  { code: 'BDJ', name: 'Kayankulam Junction', city: 'Kayankulam' },
  { code: 'NIL', name: 'Nilambur Road', city: 'Nilambur' },
  { code: 'MAO', name: 'Madgaon Junction', city: 'Goa' },
  { code: 'GOA', name: 'Vasco da Gama', city: 'Vasco' },
  { code: 'THVM', name: 'Thivim', city: 'Thivim' },
  { code: 'ASR', name: 'Amritsar Junction', city: 'Amritsar' },
  { code: 'JUC', name: 'Jalandhar City', city: 'Jalandhar' },
  { code: 'LDH', name: 'Ludhiana Junction', city: 'Ludhiana' },
  { code: 'FZR', name: 'Firozpur Cantt', city: 'Firozpur' },
  { code: 'PGW', name: 'Phagwara Junction', city: 'Phagwara' },
  { code: 'PTA', name: 'Pathankot', city: 'Pathankot' },
  { code: 'SIR', name: 'Sirhind', city: 'Sirhind' },
  { code: 'KKP', name: 'Kapurthala', city: 'Kapurthala' },
  { code: 'MOW', name: 'Moga', city: 'Moga' },
  { code: 'DUI', name: 'Dhuri Junction', city: 'Dhuri' },
  { code: 'UMB', name: 'Ambala Cantt', city: 'Ambala' },
  { code: 'PAN', name: 'Panipat Junction', city: 'Panipat' },
  { code: 'KUN', name: 'Karnal', city: 'Karnal' },
  { code: 'ROK', name: 'Rohtak Junction', city: 'Rohtak' },
  { code: 'HSR', name: 'Hisar Junction', city: 'Hisar' },
  { code: 'BNW', name: 'Bhiwani', city: 'Bhiwani' },
  { code: 'SNP', name: 'Sonipat', city: 'Sonipat' },
  { code: 'BDZ', name: 'Palwal', city: 'Palwal' },
  { code: 'SLR', name: 'Shimla', city: 'Shimla' },
  { code: 'KAL', name: 'Kalka', city: 'Kalka' },
  { code: 'CDG', name: 'Chandigarh', city: 'Chandigarh' },
  { code: 'SML', name: 'Summer Hill', city: 'Shimla' },
  { code: 'PLM', name: 'Palampur', city: 'Palampur' },
  { code: 'NIR', name: 'Nangal Dam', city: 'Nangal' },
  { code: 'JAT', name: 'Jammu Tawi', city: 'Jammu' },
  { code: 'SVDK', name: 'Shri Mata Vaishno Devi Katra', city: 'Katra' },
  { code: 'BJP', name: 'Banihal', city: 'Banihal' },
  { code: 'DDN', name: 'Dehradun', city: 'Dehradun' },
  { code: 'HRW', name: 'Haridwar Junction', city: 'Haridwar' },
  { code: 'RKSH', name: 'Rishikesh', city: 'Rishikesh' },
  { code: 'LKU', name: 'Lalkuan Junction', city: 'Lalkuan' },
  { code: 'KGM', name: 'Kathgodam', city: 'Kathgodam' },
  { code: 'HDO', name: 'Haldwani', city: 'Haldwani' },
  { code: 'GHY', name: 'Guwahati', city: 'Guwahati' },
  { code: 'KXL', name: 'Kamakhya Junction', city: 'Guwahati' },
  { code: 'NBQ', name: 'New Bongaigaon', city: 'Bongaigaon' },
  { code: 'RPAN', name: 'Rangapara North', city: 'Rangapara' },
  { code: 'SLGR', name: 'Simaluguri Junction', city: 'Simaluguri' },
  { code: 'NTSK', name: 'New Tinsukia Junction', city: 'Tinsukia' },
  { code: 'DBRT', name: 'Dibrugarh Town', city: 'Dibrugarh' },
  { code: 'LHR', name: 'Lumding Junction', city: 'Lumding' },
  { code: 'JPG', name: 'Jorhat Town', city: 'Jorhat' },
  { code: 'MXN', name: 'Mariani Junction', city: 'Mariani' },
  { code: 'MGR', name: 'Mangaldoi', city: 'Mangaldoi' },
  { code: 'RNY', name: 'Rangiya Junction', city: 'Rangiya' },
  { code: 'BPB', name: 'Badarpur Junction', city: 'Badarpur' },
  { code: 'DMV', name: 'Dimapur', city: 'Dimapur' },
  { code: 'AGTL', name: 'Agartala', city: 'Agartala' },
  { code: 'SCL', name: 'Silchar', city: 'Silchar' },
  { code: 'LEDO', name: 'Ledo', city: 'Ledo' },
  { code: 'NAO', name: 'Naharlagun', city: 'Itanagar' },
  { code: 'R', name: 'Raipur Junction', city: 'Raipur' },
  { code: 'BSP', name: 'Bilaspur Junction', city: 'Bilaspur' },
  { code: 'DURG', name: 'Durg Junction', city: 'Durg' },
  { code: 'RIG', name: 'Raigarh', city: 'Raigarh' },
  { code: 'CPH', name: 'Champa Junction', city: 'Champa' },
  { code: 'KHS', name: 'Kharsia', city: 'Kharsia' },
  { code: 'SKT', name: 'Sakti', city: 'Sakti' },
  { code: 'ABKP', name: 'Ambikapur', city: 'Ambikapur' },
  { code: 'BTF', name: 'Bhatapara', city: 'Bhatapara' },
  { code: 'GJEL', name: 'Gangtok', city: 'Gangtok' },
  { code: 'KPRR', name: 'Katakhal Junction', city: 'Katakhal' },
];
const AI_RESPONSES = {
  'kerala': '**Amazing choice! Here\'s your Kerala itinerary:**\n\n**Day 1:** Arrive Kochi by Rajdhani Express\n- Visit Fort Kochi & Chinese Fishing Nets\n- Evening Kathakali show\n\n**Day 2:** Kochi â†’ Alleppey\n- Board houseboat by noon\n- Overnight backwater cruise\n\n**Day 3:** Alleppey â†’ Munnar\n- Tea plantations tour\n- Eravikulam National Park\n\n**Day 4:** Munnar â†’ Kochi â†’ Depart\n\n**Budget:** Rs. 35,000 - Rs. 45,000 (2 people)\n**Recommended Trains:** Kerala Express (12625), Rajdhani to Ernakulam',
  'varanasi': '**Varanasi Spiritual Journey - 4 Days:**\n\n**Day 1:** Delhi â†’ Varanasi\n- Evening Ganga Aarti at Dashashwamedh Ghat\n\n**Day 2:** Full Day Varanasi\n- Sunrise boat ride on Ganges\n- Kashi Vishwanath Temple\n- Sarnath\n\n**Day 3:** Varanasi â†’ Prayagraj\n- Triveni Sangam\n\n**Day 4:** Departure\n\n**Train:** Vande Bharat Express (22438)\n**Budget:** Rs. 15,000 - Rs. 20,000 per person',
  'rajasthan': '**7-Day Rajasthan Heritage Tour:**\n\n**Day 1-2:** Jaipur - Amber Fort, City Palace, Hawa Mahal\n**Day 3:** Jaipur â†’ Jodhpur - Mehrangarh Fort\n**Day 4-5:** Jaisalmer - Fort, Desert Safari\n**Day 6-7:** Udaipur - City Palace, Lake Pichola\n\n**Budget:** Rs. 50,000 - Rs. 70,000 per person',
  'goa': '**Budget Delhi to Goa:**\n\n**Goa Express (12780)** - Sleeper Rs. 655\n\n**Must Visit:** Baga Beach, Basilica of Bom Jesus, Dudhsagar Falls\n\n**Total: Rs. 4,500 - Rs. 7,000** for 3 nights',
  'kolkata': '**Kolkata & Darjeeling Food Tour (5 Days):**\n\n**Day 1-2:** Kolkata Food Trail - K.C. Das, 6 Ballygunge Place\n**Day 3-5:** Darjeeling - Toy Train, Tiger Hill, Tea Estate\n\n**Train:** 12313 Sealdah Rajdhani\n**Budget:** Rs. 20,000 - Rs. 25,000 per person',
  'coorg': '**Bangalore to Coorg Weekend (2N/3D):**\n\n**Day 1:** Night bus/train to Coorg\n**Day 2:** Raja\'s Seat, Dubare Elephant Camp, Coffee plantation\n**Day 3:** Talakaveri, Return\n\n**Budget:** Rs. 5,000 - Rs. 8,000 per person'
};

